In [1]:
#Import the needed libraries
import pandas as pd
import numpy as np

# Data Preparation

In [3]:
#Load the data from the CSV file

puget = pd.read_csv('data_file_2015_NSC_records.csv')

#Look at the first five rows of the data

puget.head()

Student_ID Enrollment_Term Term_Type Student_Academic_Career  \
0         465       Fall 2015      Fall           Undergraduate   
1         465       Fall 2015      Fall           Undergraduate   
2         465       Fall 2015      Fall                    UGRD   
3         465       Fall 2015      Fall                    UGRD   
4         465       Fall 2015      Fall                    UGRD   

   Degree_Seeking        Study_Form Academic_Load_Term_Start  \
0  Degree Seeking  Class Enrollment                Full-Time   
1  Degree Seeking  Class Enrollment                Full-Time   
2             DEG              ENRL                        F   
3             DEG              ENRL                        F   
4             DEG              ENRL                        F   

  Academic_Load_Term_End  FTE_for_Reporting Expected_Graduation  ...  \
0              Full-Time                  1         Spring 2019  ...   
1              Full-Time                  1         Spring 2019  ...   
2                      F                  1         Spring 2019  ...   
3                      F                  1         Spring 2019  ...   
4                      F                  1         Spring 2019  ...   

  NSC_College_State NSC_College_Sequence NSC_2_Year_or_4_Year  \
0                WA                  1.0                  4.0   
1                WA                  1.0                  4.0   
2                WA                  1.0                  4.0   
3                WA                  1.0                  4.0   
4                WA                  1.0                  4.0   

  NSC_Public_or_Private NSC_Enrollment_Begin  NSC_Enrollment_End  \
0               Private           20150831.0          20151218.0   
1               Private           20160119.0          20160513.0   
2               Private           20160516.0          20160812.0   
3               Private           20160829.0          20161216.0   
4               Private           20170117.0          20170512.0   

   NSC_Graduated NSC_Degree_Title  NSC_Degree_Major_1  NSC_Degree_Major_2  
0              N              NaN                 NaN                 NaN  
1              N              NaN                 NaN                 NaN  
2              N              NaN                 NaN                 NaN  
3              N              NaN                 NaN                 NaN  
4              N              NaN                 NaN                 NaN  

[5 rows x 24 columns]

In [4]:
# ind the total number of rows
total_rows = puget.shape[0]

print(f"Total number of rows in the dataset: {total_rows}")

Total number of rows in the dataset: 5621


In [5]:
#Examine if there are any missing values in the data
print(puget.isnull().sum())
#There are a lot of missing data in the NSC columns 

Student_ID                     0
Enrollment_Term                0
Term_Type                      0
Student_Academic_Career        0
Degree_Seeking                 0
Study_Form                     0
Academic_Load_Term_Start       0
Academic_Load_Term_End         0
FTE_for_Reporting              0
Expected_Graduation            0
Major                          0
NSC_Record_Found               0
NSC_College_Code               7
NSC_College_Name               7
NSC_College_State              7
NSC_College_Sequence           7
NSC_2_Year_or_4_Year           7
NSC_Public_or_Private          7
NSC_Enrollment_Begin         454
NSC_Enrollment_End           454
NSC_Graduated                  0
NSC_Degree_Title            5178
NSC_Degree_Major_1          5178
NSC_Degree_Major_2          5541
dtype: int64


# Data Exploration/ Validation/ Cleaning

In [7]:
#1
#Find all unique values in the 'Student_ID' column
unique_values_Student_ID = puget['Student_ID'].unique()
unique_values_Student_ID

array([465, 567, 355, 227, 269,  10,  15, 354, 554, 520, 311, 107, 222,
       582, 455, 556, 200, 312, 597, 151, 607, 561,   7, 536, 443, 430,
       116, 408, 302, 215, 105, 108,  34,  98,  37, 631,  21, 149, 485,
       427, 605,  96, 534, 591, 409, 568, 231, 333, 571, 421, 255,  39,
       613,  75, 417,  92, 220, 344, 179,  86, 115, 258, 547,  84, 426,
       358, 566, 603, 495, 445, 533, 363, 428, 125, 470, 247, 498, 334,
       418,  29, 284, 522, 232,  47, 322, 382, 102, 516, 130, 133, 621,
       479,  80, 110,  64, 512, 111, 296, 482, 249, 501, 457, 584, 329,
       416, 188, 456, 581, 410, 318, 245, 464, 602,   9, 332, 267, 148,
       493, 235,  28, 328, 606, 320, 183, 623, 519, 303, 138, 376, 201,
       118, 315, 114, 326, 144, 549,  99, 234, 288, 223, 327,   2, 213,
       169, 370, 192,  78, 504,  90, 451, 488, 158, 348, 268, 260, 225,
       242,  33, 289, 460, 510, 319, 629, 525,  16, 297, 251, 121, 157,
       531, 379, 446, 142, 257, 310, 371, 173, 170, 406, 198, 60

In [8]:
#Find if there are duplicates the 'Student_ID' column
duplicates = puget['Student_ID'].duplicated(keep=False)
duplicates

0       True
1       True
2       True
3       True
4       True
        ... 
5616    True
5617    True
5618    True
5619    True
5620    True
Name: Student_ID, Length: 5621, dtype: bool

In [9]:
#Extract all duplicated Student_IDs
duplicate_ids = puget[duplicates]['Student_ID']
duplicate_ids

0       465
1       465
2       465
3       465
4       465
       ... 
5616    593
5617    593
5618    593
5619    593
5620    593
Name: Student_ID, Length: 5601, dtype: int64

In [10]:
#2
#Find all unique values in the 'Enrollment_Term' column
unique_values_Enrollment_Type = puget['Enrollment_Term'].unique()
unique_values_Enrollment_Type


array(['Fall 2015', '2158'], dtype=object)

In [11]:
#Change the values '2158' to 'Fall 2015'
puget['Enrollment_Term'] = puget['Enrollment_Term'].replace('2158', 'Fall 2015')

In [12]:
#Check again 
#Find all unique values in the 'Enrollment_Term' column
unique_values_Enrollment_Type = puget['Enrollment_Term'].unique()
unique_values_Enrollment_Type

array(['Fall 2015'], dtype=object)

In [13]:
#3
#Find all unique values in the 'Term_Type' column
unique_values_Term_Type = puget['Term_Type'].unique()
unique_values_Term_Type


array(['Fall'], dtype=object)

In [14]:
#4
#Find all unique values in the 'Student_Academic_Career' column
unique_values_Student_Academic_Career = puget['Student_Academic_Career'].unique()
unique_values_Student_Academic_Career

array(['Undergraduate', 'UGRD', 'Undergrad'], dtype=object)

In [15]:
#Change the values of 'UGRD', 'Undergrad' to 'Undergraduate'
puget['Student_Academic_Career'] = puget['Student_Academic_Career'].replace({'UGRD': 'Undergraduate', 'Undergrad': 'Undergraduate'})

In [16]:
#Check again
#Find all unique values in the 'Student_Academic_Career' column
unique_values_Student_Academic_Career = puget['Student_Academic_Career'].unique()
unique_values_Student_Academic_Career

array(['Undergraduate'], dtype=object)

In [17]:
#5
#Find all unique values in the 'Degree_Seeking' column
unique_values_Student_Degree_Seeking = puget['Degree_Seeking'].unique()
unique_values_Student_Degree_Seeking

array(['Degree Seeking', 'DEG', 'Degree'], dtype=object)

In [18]:
#Change the values of 'Degree Seeking', 'DEG' to 'Degree'
puget['Degree_Seeking'] = puget['Degree_Seeking'].replace({'Degree Seeking': 'Degree', 'DEG': 'Degree'})

In [19]:
#Check again
#Find all unique values in the 'Degree_Seeking' column
unique_values_Student_Degree_Seeking = puget['Degree_Seeking'].unique()
unique_values_Student_Degree_Seeking

array(['Degree'], dtype=object)

In [20]:
#6
#Find all unique values in the 'Study_Form' column
unique_values_Study_Form = puget['Study_Form'].unique()
unique_values_Study_Form

array(['Class Enrollment', 'ENRL', 'Enrolled'], dtype=object)

In [21]:
#Change the values of 'Class Enrollment', 'ENRL' to 'Enrolled'
puget['Study_Form'] = puget['Study_Form'].replace({'Class Enrollment': 'Enrolled', 'ENRL': 'Enrolled'})

In [22]:
#Check again 
#Find all unique values in the 'Study_Form' column
unique_values_Study_Form = puget['Study_Form'].unique()
unique_values_Study_Form

array(['Enrolled'], dtype=object)

In [23]:
#7
#Find all unique values in the 'Academic_Load_Term_Start' column
unique_values_Academic_Load_Term_Start = puget['Academic_Load_Term_Start'].unique()
unique_values_Academic_Load_Term_Start


array(['Full-Time', 'F', 'FT'], dtype=object)

In [24]:
#Change the values of 'Full-Time', 'F' to 'FT'
puget['Academic_Load_Term_Start'] = puget['Academic_Load_Term_Start'].replace({'Full-Time': 'FT', 'F': 'FT'})

In [25]:
#Check again
#Find all unique values in the 'Academic_Load_Term_Start' column
unique_values_Academic_Load_Term_Start = puget['Academic_Load_Term_Start'].unique()
unique_values_Academic_Load_Term_Start

array(['FT'], dtype=object)

In [26]:
#8
#Find all unique values in the 'Academic_Load_Term_End' column
unique_values_Academic_Load_Term_End = puget['Academic_Load_Term_End'].unique()
unique_values_Academic_Load_Term_End

array(['Full-Time', 'F', 'Not Enrolled', 'Part-Time', 'FT', 'NONE', 'PT'],
      dtype=object)

In [27]:
#Change the values of 'Full-Time' and 'F' to 'FT'; 'Part-Time' to 'PT; 'NONE' to 'Not Enrolled'
puget['Academic_Load_Term_End'] = puget['Academic_Load_Term_End'].replace({'Full-Time': 'FT', 'F': 'FT',
                                                                              'Part-Time': 'PT', 'NONE': 'Not Enrolled'})


In [28]:
#Check again
#Find all unique values in the 'Academic_Load_Term_End' column
unique_values_Academic_Load_Term_End = puget['Academic_Load_Term_End'].unique()
unique_values_Academic_Load_Term_End

array(['FT', 'Not Enrolled', 'PT'], dtype=object)

In [29]:
#9
#Find all unique values in the 'FTE_for_Reporting' column
unique_values_FTE_for_Reporting = puget['FTE_for_Reporting'].unique()
unique_values_FTE_for_Reporting

array([1], dtype=int64)

In [30]:
#10
#Find all unique values in the 'Expected_Graduation' column
unique_values_Expected_Graduation = puget['Expected_Graduation'].unique()
unique_values_Expected_Graduation


array(['Spring 2019', '2194'], dtype=object)

In [31]:
#Change the value of '2194' to 'Spring 2019'
puget['Expected_Graduation'] = puget['Expected_Graduation'].replace('2194', 'Spring 2019')

In [32]:
#Check again
#Find all unique values in the 'Expected_Graduation' column
unique_values_Expected_Graduation = puget['Expected_Graduation'].unique()
unique_values_Expected_Graduation

array(['Spring 2019'], dtype=object)

In [33]:
#11
#Find all unique values in the 'Major' column
unique_values_Major = puget['Major'].unique()
unique_values_Major

#BLP (Business Leadership Program leading to a Bachelor of Arts degree

array(['Undeclared', 'BLP (BA)'], dtype=object)

In [34]:
#12
#Find all unique values in the 'NSC_Record_Found' column
unique_values_NSC_Record_Found = puget['NSC_Record_Found'].unique()
unique_values_NSC_Record_Found

array(['Y', 'YES', 'Yes', 'yes', 'NO', 'no', 'N'], dtype=object)

In [35]:
#Check the values of 'Y', 'Yes' and 'yes' to 'YES'; 'no' and 'N' to 'NO'
puget['NSC_Record_Found'] = puget['NSC_Record_Found'].replace({'Y': 'YES', 'Yes': 'YES', 'yes': 'YES',
                                                               'no': 'NO', 'N': 'NO'})

In [36]:
#Check again
#Find all unique values in the 'NSC_Record_Found' column
unique_values_NSC_Record_Found = puget['NSC_Record_Found'].unique()
unique_values_NSC_Record_Found

array(['YES', 'NO'], dtype=object)

In [37]:
#13
#Find all unique values in the 'NSC_College_Code' column
unique_values_NSC_College_Code = puget['NSC_College_Code'].unique()
unique_values_NSC_College_Code

array(['003797-00', '002171-00', '002144-00', '003407-00', '001191-00',
       '003798-00', '003787-00', '006777-00', '002532-00', '001320-00',
       '001166-00', '022427-00', '001233-00', '011161-00', '001232-00',
       '038713-00', '001286-00', '002130-00', '001178-00', '007115-00',
       '001199-00', '003005-00', '003835-00', '001124-00', '001287-00',
       '010395-00', '001203-00', '011649-00', '001326-00', '006973-00',
       '001312-00', '001150-00', '001151-00', '001275-00', '001758-00',
       '001774-00', '002565-00', '004480-00', '012452-00', '001181-00',
       '001434-00', '001321-00', '001334-00', '011820-00', '008903-00',
       '009542-00', '004509-00', '002199-00', '001948-00', '004508-00',
       '001346-00', '001360-00', '002920-00', '001611-00', '001610-00',
       '001616-00', '003681-00', '042118-00', '001626-00', '003769-00',
       '003219-00', '010182-00', '003223-00', '003211-00', '003198-00',
       '003213-00', '003216-00', '004878-00', '003875-00', '0032

In [38]:
#14
#Find all unique values in the 'NSC_College_Name' column
unique_values_NSC_College_Name = puget['NSC_College_Name'].unique()
unique_values_NSC_College_Name

array(['UNIVERSITY OF PUGET SOUND', 'MASSACHUSETTS BAY COMMUNITY COLLEGE',
       'DEAN COLLEGE', 'RHODE ISLAND COLLEGE', 'DIABLO VALLEY COLLEGE',
       'UNIVERSITY OF WASHINGTON - SEATTLE', 'SEATTLE CENTRAL COLLEGE',
       'FLATHEAD VALLEY COMMUNITY COLLEGE',
       'MONTANA STATE UNIVERSITY - BOZEMAN',
       'UNIVERSITY OF CALIFORNIA-SANTA BARBARA', 'CITRUS COLLEGE',
       'BERKELEY CITY COLLEGE',
       'SACRAMENTO CITY COLLEGE-LOS RIOS CC DISTRICT',
       'TEXAS A&M UNIVERSITY - CORPUS CHRISTI',
       'AMERICAN RIVER COLLEGE LOS RIOS CC DISTRICT',
       'FOLSOM LAKE COLLEGE', 'SANTA MONICA COLLEGE', 'BOSTON UNIVERSITY',
       'COLLEGE OF MARIN', 'MOORPARK COLLEGE', 'FOOTHILL COLLEGE',
       'UNIVERSITY OF NORTH DAKOTA', 'BELOIT COLLEGE', 'CABRILLO COLLEGE',
       'SANTA ROSA JUNIOR COLLEGE', 'UNIVERSITY OF SAN DIEGO',
       'GLENDALE COMMUNITY COLLEGE', 'LOYOLA MARYMOUNT UNIVERSITY',
       'SANTA CLARA UNIVERSITY', 'CANADA COLLEGE',
       'UNIVERSITY OF CALIFORNIA - BE

In [39]:
#15
#Find all unique values in the 'NSC_College_State' column
unique_values_NSC_College_State = puget['NSC_College_State'].unique()
unique_values_NSC_College_State

array(['WA', 'MA', 'RI', 'CA', 'MT', 'TX', 'ND', 'WI', 'IL', 'NE', 'DC',
       'CO', 'KS', 'NC', 'HI', 'ID', 'UT', 'OR', 'NY', 'MO', 'PA', nan,
       'FL', 'MI', 'NM', 'TN', 'NV', 'MN', 'AL', 'AK', 'OH', 'MD', 'CT',
       'AZ', 'GA', 'LA', 'NJ', 'SC'], dtype=object)

In [40]:
#16
#Find all unique values in the 'NSC_College_Sequence' column
unique_values_NSC_College_Sequence = puget['NSC_College_Sequence'].unique()
unique_values_NSC_College_Sequence

array([ 1.,  2.,  3.,  4.,  5., nan])

In [41]:
#17
#Find all unique values in the 'NSC_2_Year_or_4_Year' column
unique_values_NSC_2_Year_or_4_Year = puget['NSC_2_Year_or_4_Year'].unique()
unique_values_NSC_2_Year_or_4_Year

array([ 4.,  2., nan])

In [42]:
#18
#Find all unique values in the 'NSC_Public_or_Private' column
unique_values_NSC_Public_or_Private = puget['NSC_Public_or_Private'].unique()
unique_values_NSC_Public_or_Private

array(['Private', 'Public', nan], dtype=object)

In [43]:
#19
#Find all unique values in the 'NSC_Enrollment_Begin' column
unique_values_NSC_Enrollment_Begin = puget['NSC_Enrollment_Begin'].unique()
unique_values_NSC_Enrollment_Begin

array([20150831., 20160119., 20160516., 20160829., 20170117., 20170515.,
       20170828., 20180116., 20180827., 20190122.,       nan, 20160523.,
       20150518., 20130122., 20150112., 20170103., 20170327., 20170927.,
       20180103., 20180326., 20180926., 20190107., 20190401., 20160926.,
       20140609., 20140828., 20180110., 20190109., 20170928., 20180402.,
       20180927., 20160620., 20170626., 20180514., 20180618., 20140823.,
       20170905., 20180529., 20180702., 20160820., 20170114., 20170605.,
       20140118., 20150117., 20180212., 20190101., 20190211., 20180118.,
       20180904., 20190521., 20140818., 20130819., 20140106., 20140520.,
       20050926., 20060410., 20060925., 20070409., 20070924., 20080107.,
       20080922., 20090105., 20090406., 20100104., 20100405., 20110103.,
       20120822., 20160822., 20170116., 20180122., 20190121., 20190128.,
       20170821., 20180117., 20180820., 20160606., 20170109., 20170410.,
       20170906., 20180129., 20180905., 20190103., 

In [44]:
#20
#Find all unique values in the 'NSC_Enrollment_End' column
unique_values_NSC_Enrollment_End = puget['NSC_Enrollment_End'].unique()
unique_values_NSC_Enrollment_End

array([20151218., 20160513., 20160812., 20161216., 20170512., 20170811.,
       20171215., 20180511., 20181214., 20190517.,       nan, 20160819.,
       20150813., 20130513., 20150520., 20170317., 20170609., 20180316.,
       20180608., 20190322., 20190614., 20161215., 20140815., 20141218.,
       20180504., 20190503., 20180112., 20180323., 20180615., 20170818.,
       20180810., 20180726., 20171206., 20180502., 20180629., 20180803.,
       20181205., 20170517., 20170803., 20140521., 20171219., 20180612.,
       20181218., 20190207., 20190611., 20171221., 20181221., 20190511.,
       20190627., 20141213., 20131218., 20140519., 20140808., 20141217.,
       20051216., 20060630., 20061215., 20070629., 20071214., 20080328.,
       20081212., 20090327., 20090626., 20100326., 20100625., 20110325.,
       20121221., 20161213., 20170509., 20180515., 20190514., 20181215.,
       20190525., 20171222., 20180525., 20160916., 20170331., 20170630.,
       20180523., 20190123., 20190523., 20180824., 

In [45]:
#21
#Find all unique values in the 'NSC_Graduated' column
unique_values_NSC_Graduated = puget['NSC_Graduated'].unique()
unique_values_NSC_Graduated

array(['N', 'Y'], dtype=object)

In [46]:
#Change 'N' to 'NO' and 'Y' to 'YES"
puget['NSC_Graduated'] = puget['NSC_Graduated'].replace({'N': 'NO', 'Y': 'YES'})

In [47]:
#Check again
#Find all unique values in the 'NSC_Graduated' column
unique_values_NSC_Graduated = puget['NSC_Graduated'].unique()
unique_values_NSC_Graduated

array(['NO', 'YES'], dtype=object)

In [48]:
#22
#Find all unique values in the 'NSC_Degree_Title' column
unique_values_NSC_Degree_Title = puget['NSC_Degree_Title'].unique()
unique_values_NSC_Degree_Title

array([nan, 'BACHELOR OF SCIENCE', 'BACHELOR OF ARTS', 'BS',
       'ASSOCIATE IN ARTS', 'ASSOCIATE IN SCIENCE',
       'CERTIFICATE 30 - 59.99 UNITS', 'BACHELOR OF MUSIC',
       'ASSOCIATE ARTS & SCIENCES- DTA', 'BA',
       'ASSOC OF ARTS - (AA - DTA)', 'ASSOCIATE DEGREE',
       'ASSOCIATE IN ARTS- DTA#', 'BS  LIBERAL ARTS AND SCIENCE', 'B S',
       'BACHELOR OF SCI IN AGRICULTURE', 'CERTIFICATE OF ACHIEVEMENT',
       'EMERGENCY CARE FOR FIRST RESPONDERS CERTIFICATE',
       'EMERGENCY MEDICAL TECHNICIAN (EMT-BASIC) CERTIFICATE'],
      dtype=object)

In [49]:
#23
#Find all unique values in the 'NSC_Degree_Major_1' column
unique_values_NSC_Degree_Major_1 = puget['NSC_Degree_Major_1'].unique()
unique_values_NSC_Degree_Major_1

array([nan, 'COMPUTER SCI/BUSINESS (BS)', 'ENGLISH (BA)',
       'PSYCHOLOGY (BA)', 'INTL POLITICAL ECON (BA)',
       'MATHEMATICS (STANDARD) (BS)', 'BIOLOGY (BS)',
       'ENGLISH (CR. WRITING FOCUS)', 'COMPUTER SCI (STANDARD) (BS)',
       'BLP (BA)', 'POLITICAL SCIENCE', 'POL & GOVT (U.S.) (BA)',
       'ART STUDIO (PAINTING) (BA)', 'BIOMEDICAL SCIENCES',
       'MOLECULAR AND CELL BIOL (BS)', 'BIOCHEMISTRY (BS)',
       'BUSINESS ADMINISTRATION (BA)', 'ECONOMICS (BA)', 'ECONOMICS (BS)',
       'MOLECULAR CELLULAR AND INTEGRATIVE BIOLOGY',
       'NATURAL SCIENCE (BIOL) (BS)', 'HISTORY (BA)', 'MATHEMATICS',
       'BUS ADMIN-TRANSFER(CSU GE)', 'CSU GENERAL ED', 'GEOLOGY (BS)',
       'COMMUNICATION STUDIES (BA)', 'CLASSICS (LANGUAGE) (BA)',
       'NATURAL SCIENCE (GEOL) (BS)', 'PHYSICS (BS)',
       'CHINESE (LANG/CULTURE) (BA)', 'SOCIOLOGY & ANTHROPOLOGY (BA)',
       'COMPUTER SCI (CONTRACT) (BS)', 'POL & GOVT (INTRNTL) (BA)',
       'RELIGIOUS STUDIES (BA)', 'MUSIC (BA)', 'CHEM

In [50]:
#24
#Find all unique values in the 'NSC_Degree_Major_2' column
unique_values_NSC_Degree_Major_2 = puget['NSC_Degree_Major_2'].unique()
unique_values_NSC_Degree_Major_2

array([nan, 'BUSINESS (GENERAL) (BA)', 'HISTORY (BA)',
       'INTL POLITICAL ECON (BA)', 'MATHEMATICS (STANDARD) (BS)',
       'SPANISH CULTURE AND LIT (BA)', 'POL & GOVT (COMPARATIVE) (BA)',
       'COMMUNICATION STUDIES (BA)', 'ENGLISH (CR WRIT FOCUS) (BA)',
       'ENVR POLICY & DEC MKG (BA)', 'BUSINESS ADMINISTRATION (BA)',
       'CHINESE (LANG/CULTURE) (BA)', 'PERFORMANCE (ORCH) (BM)',
       'GERMAN STUDIES (BA)', 'AFRICAN-AMERICAN STUDIES (BA)',
       'ECONOMICS (BA)', 'MUSIC (BA)', 'THEATRE ARTS (BA)',
       'FRENCH (MUSIC FOCUS) (BA)', 'SOCIOLOGY & ANTHROPOLOGY (BA)',
       'JAPANESE (LANG/CULTURE) (BA)', 'ART (STUDIO - PAINTING) (BA)',
       'PHILOSOPHY (BA)', 'POL & GOVT (U.S.) (BA)',
       'POL & GOVT (INTRNTL) (BA)', 'FRENCH (ART FOCUS) (BA)',
       'CHEMISTRY (BA)', 'PHYSICS (BS)'], dtype=object)

In [51]:
puget.head()

Student_ID Enrollment_Term Term_Type Student_Academic_Career  \
0         465       Fall 2015      Fall           Undergraduate   
1         465       Fall 2015      Fall           Undergraduate   
2         465       Fall 2015      Fall           Undergraduate   
3         465       Fall 2015      Fall           Undergraduate   
4         465       Fall 2015      Fall           Undergraduate   

  Degree_Seeking Study_Form Academic_Load_Term_Start Academic_Load_Term_End  \
0         Degree   Enrolled                       FT                     FT   
1         Degree   Enrolled                       FT                     FT   
2         Degree   Enrolled                       FT                     FT   
3         Degree   Enrolled                       FT                     FT   
4         Degree   Enrolled                       FT                     FT   

   FTE_for_Reporting Expected_Graduation  ... NSC_College_State  \
0                  1         Spring 2019  ...                WA   
1                  1         Spring 2019  ...                WA   
2                  1         Spring 2019  ...                WA   
3                  1         Spring 2019  ...                WA   
4                  1         Spring 2019  ...                WA   

  NSC_College_Sequence NSC_2_Year_or_4_Year NSC_Public_or_Private  \
0                  1.0                  4.0               Private   
1                  1.0                  4.0               Private   
2                  1.0                  4.0               Private   
3                  1.0                  4.0               Private   
4                  1.0                  4.0               Private   

  NSC_Enrollment_Begin  NSC_Enrollment_End  NSC_Graduated NSC_Degree_Title  \
0           20150831.0          20151218.0             NO              NaN   
1           20160119.0          20160513.0             NO              NaN   
2           20160516.0          20160812.0             NO              NaN   
3           20160829.0          20161216.0             NO              NaN   
4           20170117.0          20170512.0             NO              NaN   

   NSC_Degree_Major_1  NSC_Degree_Major_2  
0                 NaN                 NaN  
1                 NaN                 NaN  
2                 NaN                 NaN  
3                 NaN                 NaN  
4                 NaN                 NaN  

[5 rows x 24 columns]

In [52]:
#Select and display the row #1
first_row = puget.iloc[0]
first_row


Student_ID                                        465
Enrollment_Term                             Fall 2015
Term_Type                                        Fall
Student_Academic_Career                 Undergraduate
Degree_Seeking                                 Degree
Study_Form                                   Enrolled
Academic_Load_Term_Start                           FT
Academic_Load_Term_End                             FT
FTE_for_Reporting                                   1
Expected_Graduation                       Spring 2019
Major                                      Undeclared
NSC_Record_Found                                  YES
NSC_College_Code                            003797-00
NSC_College_Name            UNIVERSITY OF PUGET SOUND
NSC_College_State                                  WA
NSC_College_Sequence                              1.0
NSC_2_Year_or_4_Year                              4.0
NSC_Public_or_Private                         Private
NSC_Enrollment_Begin        

In [53]:
#Select the row(s) where the 'NSC_College_Name' is 'UNIVERSITY OF SAN FRANCISCO'
usf_rows = puget[puget['NSC_College_Name'] == 'UNIVERSITY OF SAN FRANCISCO']
usf_rows

Student_ID Enrollment_Term Term_Type Student_Academic_Career  \
2368         543       Fall 2015      Fall           Undergraduate   

     Degree_Seeking Study_Form Academic_Load_Term_Start  \
2368         Degree   Enrolled                       FT   

     Academic_Load_Term_End  FTE_for_Reporting Expected_Graduation  ...  \
2368                     FT                  1         Spring 2019  ...   

     NSC_College_State NSC_College_Sequence NSC_2_Year_or_4_Year  \
2368                CA                  2.0                  4.0   

     NSC_Public_or_Private NSC_Enrollment_Begin  NSC_Enrollment_End  \
2368               Private           20160523.0          20160812.0   

      NSC_Graduated NSC_Degree_Title  NSC_Degree_Major_1  NSC_Degree_Major_2  
2368             NO              NaN                 NaN                 NaN  

[1 rows x 24 columns]

In [54]:
#Select and display the row #2368
row_2368 = puget.iloc[2368]
row_2368

Student_ID                                          543
Enrollment_Term                               Fall 2015
Term_Type                                          Fall
Student_Academic_Career                   Undergraduate
Degree_Seeking                                   Degree
Study_Form                                     Enrolled
Academic_Load_Term_Start                             FT
Academic_Load_Term_End                               FT
FTE_for_Reporting                                     1
Expected_Graduation                         Spring 2019
Major                                        Undeclared
NSC_Record_Found                                    YES
NSC_College_Code                              001325-00
NSC_College_Name            UNIVERSITY OF SAN FRANCISCO
NSC_College_State                                    CA
NSC_College_Sequence                                2.0
NSC_2_Year_or_4_Year                                4.0
NSC_Public_or_Private                           

In [55]:
##Select the row(s) where the 'NSC_College_Name' is 'SEATTLE CENTRAL COLLEGE'
scc_rows = puget[puget['NSC_College_Name'] == 'SEATTLE CENTRAL COLLEGE']
scc_rows


Student_ID Enrollment_Term Term_Type Student_Academic_Career  \
41           227       Fall 2015      Fall           Undergraduate   
2178         489       Fall 2015      Fall           Undergraduate   
2179         489       Fall 2015      Fall           Undergraduate   
2180         489       Fall 2015      Fall           Undergraduate   
2181         489       Fall 2015      Fall           Undergraduate   
2236         230       Fall 2015      Fall           Undergraduate   
2237         230       Fall 2015      Fall           Undergraduate   
2238         230       Fall 2015      Fall           Undergraduate   

     Degree_Seeking Study_Form Academic_Load_Term_Start  \
41           Degree   Enrolled                       FT   
2178         Degree   Enrolled                       FT   
2179         Degree   Enrolled                       FT   
2180         Degree   Enrolled                       FT   
2181         Degree   Enrolled                       FT   
2236         Degree   Enrolled                       FT   
2237         Degree   Enrolled                       FT   
2238         Degree   Enrolled                       FT   

     Academic_Load_Term_End  FTE_for_Reporting Expected_Graduation  ...  \
41                       FT                  1         Spring 2019  ...   
2178                     FT                  1         Spring 2019  ...   
2179                     FT                  1         Spring 2019  ...   
2180                     FT                  1         Spring 2019  ...   
2181                     FT                  1         Spring 2019  ...   
2236                     FT                  1         Spring 2019  ...   
2237                     FT                  1         Spring 2019  ...   
2238                     FT                  1         Spring 2019  ...   

     NSC_College_State NSC_College_Sequence NSC_2_Year_or_4_Year  \
41                  WA                  2.0                  4.0   
2178                WA                  2.0                  4.0   
2179                WA                  2.0                  4.0   
2180                WA                  2.0                  4.0   
2181                WA                  2.0                  4.0   
2236                WA                  2.0                  4.0   
2237                WA                  2.0                  4.0   
2238                WA                  2.0                  4.0   

     NSC_Public_or_Private NSC_Enrollment_Begin  NSC_Enrollment_End  \
41                  Public           20160926.0          20161215.0   
2178                Public           20120625.0          20120817.0   
2179                Public           20130624.0          20130816.0   
2180                Public           20140630.0          20140822.0   
2181                Public           20180625.0          20180817.0   
2236                Public           20120625.0          20120817.0   
2237                Public           20130624.0          20130816.0   
2238                Public           20140630.0          20140822.0   

      NSC_Graduated NSC_Degree_Title  NSC_Degree_Major_1  NSC_Degree_Major_2  
41               NO              NaN                 NaN                 NaN  
2178             NO              NaN                 NaN                 NaN  
2179             NO              NaN                 NaN                 NaN  
2180             NO              NaN                 NaN                 NaN  
2181             NO              NaN                 NaN                 NaN  
2236             NO              NaN                 NaN                 NaN  
2237             NO              NaN                 NaN                 NaN  
2238             NO              NaN                 NaN                 NaN  

[8 rows x 24 columns]

In [56]:
#Select and display the row #41
row_41 = puget.iloc[41]
row_41

Student_ID                                      227
Enrollment_Term                           Fall 2015
Term_Type                                      Fall
Student_Academic_Career               Undergraduate
Degree_Seeking                               Degree
Study_Form                                 Enrolled
Academic_Load_Term_Start                         FT
Academic_Load_Term_End                           FT
FTE_for_Reporting                                 1
Expected_Graduation                     Spring 2019
Major                                    Undeclared
NSC_Record_Found                                YES
NSC_College_Code                          003787-00
NSC_College_Name            SEATTLE CENTRAL COLLEGE
NSC_College_State                                WA
NSC_College_Sequence                            2.0
NSC_2_Year_or_4_Year                            4.0
NSC_Public_or_Private                        Public
NSC_Enrollment_Begin                     20160926.0
NSC_Enrollme

In [116]:
#Convert the pandas dataframe to an CSV file
puget.to_csv('updated_puget.csv')